name: Daily Report New

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - main


jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install
        run: pip install -r requirements.txt

      - name: Run script
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
        run: python src/run_daily.py

      - name: Deploy to Surge
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: |
          npm install --global surge
          surge ./output ${{ secrets.PUBLIC_URL }} \
            --token ${{ secrets.SURGE_TOKEN }}
